ryonakano/konbucase

meson.build, po/POTFILES, po/com.github.ryonakano.case-converter.pot, po/com.github.ryonakano.konbucase.pot, po/meson.build, src/MainWindow.vala
=> Support translation

data/com.github.ryonakano.konbucase.appdata.xml.in, data/com.github.ryonakano.konbucase.desktop.in, data/meson.build, meson.build, po/extra/POTFILES, po/extra/extra.pot, po/extra/meson.build
=> Add metadata files

data/icons/128/com.github.ryonakano.konbucase.svg, data/icons/16/com.github.ryonakano.konbucase.svg, data/icons/24/com.github.ryonakano.konbucase.svg, data/icons/32/com.github.ryonakano.konbucase.svg, data/icons/48/com.github.ryonakano.konbucase.svg, data/icons/64/com.github.ryonakano.konbucase.svg, data/meson.build, meson/post_install.py
=> Add an app icon

src/Widgets/ComboEntry.vala
=> Recalculate when changing combobox

src/Widgets/ComboEntry.vala
=> Fix the app freezes when trying to input texts in result_combo_entry

README.md, data/Application.css, meson.build, src/MainWindow.vala, src/PantheonAccountsServicePlugin.vala, src/Widgets/ComboEntry.vala
=> Respect an elementary OS-wide dark preference

meson.build, src/MainWindow.vala, src/PantheonAccountsServicePlugin.vala
As in https://github.com/ryonakano/konbucase/pull/31#issuecomment-625968771
=> Drop 'dark variant' support for Hera

src/Widgets/ComboEntry.vala
=> Add a description tooltip to each case

data/com.github.ryonakano.konbucase.gschema.xml, src/MainWindow.vala
For those who prefer dark variant on Hera :)
=> Allow to set per-app dark style preference

src/MainWindow.vala
=> Fix changing OS-wide dark style preference is not reflected

src/MainWindow.vala, src/Widgets/ComboEntry.vala
=> Side-by-side view

data/icons/128/com.github.ryonakano.konbucase.svg, data/icons/16/com.github.ryonakano.konbucase.svg, data/icons/24/com.github.ryonakano.konbucase.svg, data/icons/32/com.github.ryonakano.konbucase.svg, data/icons/48/com.github.ryonakano.konbucase.svg, data/icons/64/com.github.ryonakano.konbucase.svg
PR from #45 
Please test this first and give additional feedbacks before I pixel fit them.
=> Improving Konbucase Icon

po/LINGUAS, po/extra/LINGUAS, po/extra/tr.po, po/tr.po
=> Add Turkish translation

po/extra/nl.po, po/nl.po
=> Update Dutch translation

com.github.ryonakano.konbucase.yml, meson.build, meson_options.txt
As suggested in https://github.com/elementary/appcenter-reviews/pull/34#issuecomment-889976600
=> Use gitsubmodule for native build and modules for Flatpak

meson.build, meson_options.txt, src/Application.vala, src/StyleSwitcher.vala
=> Check desktop environment on runtime

src/StyleSwitcher.vala
Same with https://github.com/ryonakano/reco/pull/196
=> StyleSwitcher: Let system-synced color preference available on any platforms

.gitignore, README.md, com.github.ryonakano.konbucase.yml, data/konbucase.gschema.xml, src/Widgets/ComboEntry.vala, src/meson.build, subprojects/ryokucha.wrap
I didn't know we can use `set_enum ()` and `get_enum ()`
=> Use Gtk.DropDown instead of Ryokucha.DropDownText

src/Application.vala, src/MainWindow.vala
Separated independent changes from #133
=> Use string for style state

src/Application.vala
=> Application: Use const instead of static

build-aux/appcenter/com.github.ryonakano.konbucase.Devel.yml, build-aux/flathub/com.github.ryonakano.konbucase.Devel.yml, com.github.ryonakano.konbucase.yml
Flatpak External Data Checker seems to force this style, which is annoying though, so switch to it now to avoid manifest update and coding style update from being in one commit
=> Flatpak: Omit quote when possible

build-aux/appcenter/com.github.ryonakano.konbucase.Devel.yml, build-aux/flathub/com.github.ryonakano.konbucase.Devel.yml, com.github.ryonakano.konbucase.yml
I prefer archives for quick download but that should be a tiny difference in the modern fast networks
=> Flatpak: Use git for modules

src/Model/CaseListItemModel.vala, src/Model/TextPaneModel.vala, src/View/TextPane.vala, src/Widget/DropDownRow.vala, src/meson.build
=> Put description into dropdown

data/konbucase.gschema.xml.in, src/MainWindow.vala, src/View/Pane/ResultPane.vala
Make sure to perform conversion every time the app launches
=> refactor: Perform conversion instead of recovering last result on startup

data/Application.css, data/konbucase.gresource.xml.in, src/View/BasePane.vala
And now it has a subtle shadow
=> refactor: BasePane: Use Adw.ToolbarView
